autocomplete-big-list: autocomplete-big-list.o
	g++ autocomplete-big-list.o -o autocomplete-big-list

autocomplete-big-list.o: autocomplete-big-list.cpp
	g++ -std=c++11 -c autocomplete-big-list.cpp

clean:
	rm *.o autocomplete-big-list
